import type { FormControl } from "svelte-reactive-form/src/types";
export declare const required: (v: any) => boolean | string;
export declare const alphaNum: (v: string) => boolean | string;
export declare const between: (v: any, [min, max]: string[]) => boolean | string;
export declare const url: (v: string) => boolean | string;
export declare const unique: <T>(v: T[]) => boolean | string;
export declare const same: (v: any, [field]: string[], ctx: FormControl) => boolean | string;
export declare const email: (v: string) => boolean | string;
export declare const contains: <T>(v: T, list: T[]) => boolean | string;
export declare const minLength: (val: any, [min]: [number]) => boolean | string;
export declare const max: (v: any, [len]: [string]) => boolean | string;
export declare const min: (v: any, [len]: [string]) => boolean | string;
export declare const integer: (v: string) => boolean | string;
