name: Publish package to NPM
on:
  release:
    types: [created]

jobs:
  build:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Check out code from repository
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Set Current Version
        run: |
          CURRENT_VERSION=${{ github.event.release.tag_name }}
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
          echo ${{ env.CURRENT_VERSION }}

      - name: Build and Publish
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          npm i --no-save
          lerna publish ${{ env.CURRENT_VERSION }} --force-publish --no-git-tag-version --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
