# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Matrix Testing

on:
  push:
    branches:
      - main
      - sandbox
      - dev

  pull_request:
    branches:
      - main
      - sandbox
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["16", "17"]
    name: Node ${{ matrix.node }} sample
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache dependencies
        id: cache-modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: NPM Install
        if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: Run svelte-check
        run: |
          npm run check

      - name: Run jest
        run: |
          npm run test
